# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 29, 9, 7, 45, 939237, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 29, 9, 7, 45, 937688, tzinfo=utc)),
        ),
    ]
