# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.SmallIntegerField()),
                ('performance', models.SmallIntegerField()),
                ('design', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='design',
        ),
        migrations.RemoveField(
            model_name='product',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.AddField(
            model_name='comment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urun.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ManyToManyField(to='urun.Vendor'),
        ),
    ]
