# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='created_by',
        ),
    ]
