# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 07:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0002_auto_20170727_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 7, 10, 6, 943183, tzinfo=utc)),
        ),
    ]
