# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0003_product_created_date'),
        ('urun', '0003_comment_created_date'),
    ]

    operations = [
    ]
