# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0004_auto_20170802_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='design',
            field=models.SmallIntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='performance',
            field=models.SmallIntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.SmallIntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)]),
        ),
    ]
